language: python
sudo: false
python:
  - "3.8"
env:
  - PROJECT=augeias
install:
  - pip install -r requirements-dev.txt
  - python setup.py develop
script: 
  py.test --cov $PROJECT --cov-report term-missing tests
after_success:
 - coveralls
